use std::env;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ShimType {
    NativeExe,
    CmdScript,
    BatScript,
    PowerShell,
    PosixBinary,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedCommand {
    pub program: PathBuf,
    pub shim_type: ShimType,
    pub is_direct_executable: bool,
}

/// Resolves a command name by inspecting PATH and PATHEXT.
/// Correctly handles `.cmd` and `.bat` wrappers commonly generated by npm, pnpm, and cargo on Windows.
pub fn resolve_command_shim(cmd: &str) -> Option<ResolvedCommand> {
    let cmd_path = Path::new(cmd);

    // If caller provided an explicit file that exists
    if cmd_path.is_file() {
        return Some(classify_resolved_path(cmd_path.to_path_buf()));
    }

    let path_var = env::var_os("PATH")?;
    let paths = env::split_paths(&path_var);

    #[cfg(windows)]
    {
        let pathext =
            env::var("PATHEXT").unwrap_or_else(|_| ".COM;.EXE;.BAT;.CMD;.VBS;.JS;.WS;.MSC".into());
        let extensions: Vec<String> = pathext
            .split(';')
            .map(|ext| ext.trim().to_lowercase())
            .filter(|ext| !ext.is_empty())
            .collect();

        // If cmd already has an extension, search PATH directly
        if cmd_path.extension().is_some() {
            for dir in paths {
                let candidate = dir.join(cmd);
                if candidate.is_file() {
                    return Some(classify_resolved_path(candidate));
                }
            }
            return None;
        }

        // Try extensions in PATHEXT order across PATH directories
        for dir in paths {
            for ext in &extensions {
                let candidate_name = format!("{}{}", cmd, ext);
                let candidate = dir.join(candidate_name);
                if candidate.is_file() {
                    return Some(classify_resolved_path(candidate));
                }
            }
        }
    }

    #[cfg(not(windows))]
    {
        for dir in paths {
            let candidate = dir.join(cmd);
            if candidate.is_file() {
                return Some(classify_resolved_path(candidate));
            }
        }
    }

    None
}

fn classify_resolved_path(path: PathBuf) -> ResolvedCommand {
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .map(|s| s.to_lowercase())
        .unwrap_or_default();

    let shim_type = match ext.as_str() {
        "cmd" => ShimType::CmdScript,
        "bat" => ShimType::BatScript,
        "ps1" => ShimType::PowerShell,
        "exe" | "com" => ShimType::NativeExe,
        _ => {
            #[cfg(windows)]
            {
                ShimType::NativeExe
            }
            #[cfg(not(windows))]
            {
                ShimType::PosixBinary
            }
        }
    };

    let is_direct_executable = matches!(shim_type, ShimType::NativeExe | ShimType::PosixBinary);

    ResolvedCommand {
        program: path,
        shim_type,
        is_direct_executable,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_resolves_common_system_binary() {
        #[cfg(windows)]
        let target = "cmd";
        #[cfg(not(windows))]
        let target = "sh";

        let resolved = resolve_command_shim(target);
        assert!(
            resolved.is_some(),
            "System target '{target}' should resolve"
        );
        let res = resolved.unwrap();
        assert!(res.program.exists());
        assert!(res.is_direct_executable);
    }
}
